app:
  db:
    host: 127.0.01
    port: 3306
    dbname: xwj

server:
  port: 18091
  
spring:
  application:
    name: quarts-two
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://${app.db.host}:${app.db.port}/${app.db.dbname}?autoReconnect=true&failOverReadOnly=false&createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  quartz:  #quartz相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: instance_two
            instanceId: instance_id_two
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc

logging:
  level:
    jdbc: off
    jdbc.sqltiming: error #记录sql执行的时间
    root: INFO
    com.xwj: debug

      
   
