server:
   port: 8761 #eureka默认端口
spring:
   application:
      name: eureka-server 
   security: #eureka server安全认证设置    user:      name: admin
      password: admin
   
eureka: 
   client:
      register-with-eureka: false #表示是否将自己注册到Eureka Server，默认为true
      fetch-registry: false #表示是否从Eureka Server获取注册信息，默认为true
      service-url: 
         #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka,多个地址可使用 ,分隔。 
         defaultZone: http://admin:admin@localhost:${server.port}/eureka  #多台eureka server时，自己也作为一个消费者

