server:
  port: 18082
    
spring:
  application:
    name: service-consumer #应用程序名称

management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
      
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/ # 指定eureka server通信地址，注意/eureka/小尾巴不能少
  instance:
    prefer-ip-address: true #当猜测主机名时，服务器的IP地址应该在操作系统报告的主机名中使用
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}} #更改Eureka实例ID

#断路器    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false #是否开启超时(默认开启)
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #超时时间(默认1000毫秒)
            
feign:
  hystrix:
    enabled: true #打开feign对hystrix的支持
   
