app:
  db:
    host: 127.0.01
    port: 3306
    dbname: xwj
    
server:
  port: 18083
    
spring:
  application:
    name: zuul-filter #应用程序名称
    
logging:
  level:
    root: INFO
    org.hibernate: INFO
    jdbc: off
    jdbc.sqltiming: debug
    com.xwj: DEBUG
      
