server:
  port: 18095
  
spring:
  application:
    name: service-h2
  jpa:
    show-sql: true  #打印sql
  datasource:
    url: jdbc:h2:mem:xwj_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE   #mem：连接到内存
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    data: classpath:db/data.sql    #初始化表数据

      
