# 分库 + 分表(多表) + 绑定表
spring:
  shardingsphere:
    props:
      sql.show: true 
    datasource:
      names: ds0,ds1
      ds0:  #ds0 配置
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/share0?autoReconnect=true&failOverReadOnly=false&createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      ds1:   #ds1 配置
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/share1?autoReconnect=true&failOverReadOnly=false&createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456
    sharding:  
      broadcast-tables: t_dict  #指定t_dict为广播表(公共表，每个库都有该表)
      tables:
        t_order:
          actual-data-nodes: ds$->{0..1}.t_order_$->{0..1}  # 数据节点
          key-generator:
            column: id
            type: SNOWFLAKE
          # 分库策略(水平)
          database-strategy:
            inline:
              sharding-column: order_type   # 分库字段
              algorithm-expression: ds$->{order_type % 2}  # 分库算法
          # 分表策略(水平)
          table-strategy:
            inline:
              sharding-column: id   # 分表字段id
              algorithm-expression: t_order_$->{id % 2}  # 分表算法
        t_order_detail:
          actual-data-nodes: ds$->{0..1}.t_order_detail_$->{0..1}  # 数据节点
          key-generator:
            column: id
            type: SNOWFLAKE
          # 分库策略(水平)
          database-strategy:
            inline:
              sharding-column: order_type   # 分库字段
              algorithm-expression: ds$->{order_type % 2}  # 分库算法
          # 分表策略(水平)
          table-strategy:
            inline:
              sharding-column: order_id   # 分表字段id
              algorithm-expression: t_order_detail_$->{order_id % 2}  # 分表算法
