server:
  port: 18093
spring:
  profiles:
    active: 3
  application:
    name: spring-cloud-shardingsphere
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect

logging:
  level:  #日志级别控制
    jdbc: off  #日志最高级别，只打印sql及参数
    jdbc.sqltiming: info #记录sql执行的时间
    com:  #包名
      xwj: debug