app:
  db:
    host: 127.0.01
    port: 3306
    dbname: xwj
    
jasypt:
  encryptor:
        #加密秘钥
#    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ
        #设置前缀后缀
    property:
      prefix: "ENC@["
      suffix: "]"
    
    
server:
  port: 18081
  
spring:
  application:
    name: service-provider
  datasource: 
    #log4jdbc
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://${app.db.host}:${app.db.port}/${app.db.dbname}?autoReconnect=true&failOverReadOnly=false&createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://${app.db.host}:${app.db.port}/${app.db.dbname}?autoReconnect=true&failOverReadOnly=false&createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      #show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  redis:
    database: 0 #Redis数据库索引（默认为0）
    host: localhost #Redis服务器地址
    port: 6379 
    password: ## 密码（默认为空）
  cloud:    sentinel:      transport:        dashboard: localhost:8888        
     
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:admin@localhost:8761/eureka
#  instance:
#    prefer-ip-address: true #当猜测主机名时，服务器的IP地址应该在操作系统报告的主机名中使用
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}} #更改Eureka实例ID
    
    
#spring boot默认日志
logging:
  file: my.log   #日志文件名称(也可以带路径)
  level:  #日志级别控制
    jdbc: off  #日志最高级别，只打印sql及参数
    jdbc.sqltiming: debug  #记录sql执行的时间
    com:  #包名
      xwj: info
   
      
